spring:
  application:
    name: GamiLife
    version: ${project.version}

  config:
    import:
      - classpath:other-error-codes.yml
      - classpath:shared-error-codes.yml
      - classpath:auth-error-codes.yml
      - classpath:user-error-codes.yml
      - classpath:task-error-codes.yml
      - classpath:group-error-codes.yml
      - classpath:group-shop-error-codes.yml
      - classpath:gamification-error-codes.yml
      - classpath:pomodoro-error-codes.yml
      - classpath:group-task-error-codes.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    show-sql: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  threads:
    virtual:
      enabled: true

  tokens:
    jwt:
      secret: ${JWT_SECRET}
    refresh-token:
      expires-in: 604800  # 7 days
    access-token:
      expires-in: 300     # 5 min

  codes:
    verification-code:
      expires-in: 300
      resend-interval: 120
    forgot-password-code:
      expires-in: 900
      resend-interval: 120

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${FRONTEND_URL}/oauth2/callback"
            scope:
              - openid
              - profile
              - email

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  send-emails: true
  from-email: "noreply@gamilife.pl"
  from-name: "GamiLife Team"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

server:
  port: 8080
  ssl:
    enabled: false
    secure: true

app:
  invitation:
    expiration-days: 30
    invitation-url-prefix: ${FRONTEND_URL}
  frontend-urls:
    main-url: ${FRONTEND_URL}
    reset-password-url: "/reset-password"
    email-verification-url: "/verify-email"
  rate-limit:
    standard:
      requests-limit: 60
      duration-seconds: 60
    protected:
      requests-limit: 15
      duration-seconds: 60
  cookie:
    domain: gamilife.pl
  security:
    public-paths:
      - /api/v1/auth/**
      - /api/v1/oauth2/**
      - /v3/api-docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /actuator/health
  timezone:
    default: "Europe/Warsaw"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
