spring:
  application:
    name: GamiLife
    version: ${project.version}
  config:
    import:
      - classpath:other-error-codes.yml
      - classpath:shared-error-codes.yml
      - classpath:auth-error-codes.yml
      - classpath:user-error-codes.yml
      - classpath:task-error-codes.yml
      - classpath:group-error-codes.yml
      - classpath:group-shop-error-codes.yml
      - classpath:gamification-error-codes.yml
      - classpath:pomodoro-error-codes.yml
      - classpath:group-task-error-codes.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  tokens:
    jwt:
      secret: ${JWT_SECRET}
    refresh-token:
      expires-in: 604800  # 7 days
    access-token:
      expires-in: 300     # 5 min
  codes:
    verification-code:
      expires-in: 300
      resend-interval: 120
    forgot-password-code:
      expires-in: 900
      resend-interval: 120
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email
app:
  invitation:
    invitation-url-prefix: ${INVITATION-URL-PREFIX}
    expiration-days: 14
  frontend-urls:
    main-url: { MAIN_URL }
    reset-password-url: "/reset-password"
    email-verification-url: "/verify-email"
  rate-limit:
    standard:
      requests-limit: 60
      duration-seconds: 60
    protected:
      requests-limit: 15
      duration-seconds: 60
  security:
    public-paths:
      - /api/v1/auth/**
      - /api/v1/oauth2/**
      - /v3/api-docs/**
      - /swagger-ui.html
      - /swagger-ui/**
  timezone:
    default: "Europe/Warsaw"
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  send-emails: true
  from-email: "noreply@gamilife.pl"
  from-name: "GamiLife Team"
server:
  port: 8080
  ssl:
    enabled: false